### PR TITLE
Reintroduce `Interval`

### PR DESCRIPTION
**Pull request by jcbrinfo**
For Python 3.4 and higher, make an alias to `range`. For lower versions,
use the same definition as in the Python 2 runtime library.

Signed-off-by: jcbrinfo <jcbrinfo@users.noreply.github.com>

### CODE REVIEW

**Comment by ericvergnaud** [comment]
as discussed, this goes somewhat against the intent of this target i.e. keep close to the bleeding edge
it would be better for the code base if you can publish this from your own repo, and this would only last, I guess, a few months
so let's give this some thoughts for a few days

**Comment by jcbrinfo** [comment]
Rebased on top of `master`.

**Comment by jcbrinfo** [comment]
Here are 2 alternative ways to get `start`and `stop` under Python 3.2.

## Monkey patching
```
try:
    range.start
except AttributeError:
    _range = range
    class range(object):
        __module__ = _range.__module__
        
        def __init__(self, *args):
            self._range = _range(*args)
            if len(args) >= 3:
                self.start = args[0]
                self.stop = args[1]
                self.step = args[2]
            elif len(args) == 2:
                self.start = args[0]
                self.stop = args[1]
                self.step = 1
            else:
                self.start = 0
                self.stop = args[0]
                self.step = 1
        
        def __contains__(self, item):
            return self._range.__contains__(item)
        
        def __len__(self):
            return self._range.__len__()
        
        def __iter__(self):
            return self._range.__iter__()
        
        def __getitem__(self, index):
            return self._range.__getitem__(index)
        
        def __reduce__(self):
            return self._range.__reduce__()
        
        def __reduce_ex__(self):
            return self._range.__reduce_ex__()
        
        def __repr__(self):
            return self._range.__repr__()
        
        def __reversed__(self):
            return self._range.__reversed__()
        
        def count(self, value):
            return self._range.count(value)
        
        def index(self, *args):
            return self._range.index(*args)

    __builtins__.range = range
```

## Using available attributes
```
x = range(...)
start = x[0]
stop = x[-1] + 1
# Note : Even range(10**999)[-1] returns instantly.
```

**Comment by ericvergnaud** [comment]
What about adding the below to your code, before invoking antlr ?

__range_function__ = range

class __range_class__(list):

    def __init__(self, start, stop, step=1):
        self.extend(__range_function__(start, stop, step))
        self.start = start
        self.stop = stop
        self.step = step

__builtins__.range = __range_class__

**Comment by ericvergnaud** [comment]
the underscores are being interpreted by github, but you get it

**Comment by ericvergnaud** [comment]
```Python
__range_function__ = range

class __range_class__(list):

    def __init__(self, start, stop, step=1):
        self.extend(__range_function__(start, stop, step))
        self.start = start
        self.stop = stop
        self.step = step

__builtins__.range = __range_class__
```

**Comment by jcbrinfo** [comment]
See my first alternative. This is essentially the same idea, but I tried to keep all the original attributes of `range` (this why the code is so long).

**Comment by jcbrinfo** [comment]
Note that your solution always return an empty list with some additional attributes. `extend` seems to have no effect.

**Comment by jcbrinfo** [comment]
I personally prefer the "`stop = range[-1] + 1`" solution because its impact is limited to 1 class (`IntervalSet`) and it does not tamper `__builtins__`. However, I admit that my monkey patch can do the job too.

**Comment by ericvergnaud** [comment]
monkey patching has the benefit that it can reside in your code, rather than in the library code.
Since this is really a temporary solution for a single customer, I strongly suggest you go that tactical route.

**Comment by ericvergnaud** [comment]
Hi,
I'm closing since as discussed monkey patching works fine and avoids maintaining code for legacy versions of Python
Let me know if it's an issue.
Eric

**Pull request closed without merging**
