### PR TITLE
Make compatible with Python 3.2

### PR DESCRIPTION
**Pull request by jcbrinfo**
Allow to use the runtime library under Python versions as low as 3.2.

Signed-off-by: jcbrinfo <jcbrinfo@users.noreply.github.com>

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi jcbr.
If not already done, can you sign the contributors agreement?
Also can you split this into:
 - unicode strings, which is a no brainer
 - bogus import statements
 - the range/interval stuff
Out of curiosity, what is the rationale for NOT upgrading to 3.4?

**Comment by jcbrinfo** [comment]
The users of one of my parsers can not upgrade to 3.4 easily for bureaucratic reasons. I prefer to enhance the compatibility of the parser for the moment. If I understand correctly, you want each commit in its own PR, am I right? For the contributors agreement, I forgot to do it.

Thank you for the fast reply.

**Comment by ericvergnaud** [comment]
Yes you are correct re the prs
Another approach could be to have a 3.2 specific release, which would disappear with your users constraints 
I created the python-3 specific parser (and got numerous nasty comments from people wanting a six parser) precisely to avoid backwards compatibility, the general idea being to keep reasonably close of the bleeding edge

**Comment by jcbrinfo** [comment]
Considering only the code of `Interval` is specific to Python versions below 3.4, I thought that having to maintain yet another library would be overkill.

**Comment by ericvergnaud** [comment]
Happy to merge the non interval stuff
Re interval stuff, it's not overkill if you maintain it :-), and it's probably for a short time only...
Would that make sense? Would your users feel comfortable with a jcbr version of antlr?

**Comment by jcbrinfo** [comment]
Splitted as #31, #32, #33 and #34.

**Pull request closed without merging**
